### ISSUE TITLE
Issue related to requiring objects with Initial Letter Caps

### ISSUE THREAD

**Issue by jilvin** [zcuric/eslint-plugin-require-sort#2]
The plugin shows error while requiring objects starting in capital letters(non-exhaustive case).

index.js:
```javascript
const debug = require('debug')('eslint-plugin-require-sort_issue-test:index');
const express = require('express');
const Function1 = require('./a');

const app = express();
const port = 3000;

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.listen(port, function () {
  debug(`Example app listening on port ${port}!`);
});

Function1();
```

a.js:
```javascript
const debug = require('debug')('eslint-plugin-require-sort_issue-test:a');

const a = function () {
  debug('I am the mighty A.');
};

module.exports = a;
```

Eslint Error:
```bash
Requires should be sorted alphabetically : index.js:3:1
```

**Comment by zcuric** [comment]
@jilvin  Thanks I'll look into.

**Comment by zcuric** [comment]
@jilvin This actually desired behaviour if you are using default setup. Capital letters have higher prioritiy than lower letters and in the default setup their required to be above lower letters. To fix this, set `ignoreCase` to `true` in your `.eslintrc`.

```json
  "rules": {
    "require-sort/require-sort": [ "error", {
        "ignoreCase": true
      }]
  }
```

**Comment by jilvin** [comment]
@zcuric Thanks for the quick response. I reported the issue since it was conflicting with eslint `import order` which tries to keep relative require after package requires.

**Comment by zcuric** [comment]
@jilvin That reminds me that I should add to `README` how this plugin works with `eslint-plugin-import` and other similar plugins.

**Comment by jilvin** [comment]
@zcuric I was experimenting in adding your package within a project. I have set ignoreCase true to fix the conflicting eslint error reports.

**Comment by jilvin** [comment]
@zcuris Seems I won't be able to add the plugin to the project especially with conflicts with relative imports.

`eslint-plugin-require-sort` wants it to be at the top since the path starts with `.` while `import order` wants it to be after package imports.

**Comment by zcuric** [comment]
@jilvin You could configure `import order` rule also. Experiment a bit, see what you get.

**Comment by jilvin** [comment]
@zcuric We want relative imports to be below actual npm package imports. Kudos on your great work and support.
