### ISSUE TITLE
Is auto fix implemented?

### ISSUE THREAD

**Issue by DiegoRBaquero** [zcuric/eslint-plugin-require-sort#3]
Hey,

Thanks for the OSS package!

Wondering if the auto fix is already implemented, per https://github.com/kentor/eslint-plugin-sort-requires/issues/1

Thank you!!

**Comment by zcuric** [comment]
@DiegoRBaquero You are welcome! 👍 

Fix works only for sorting multiple exports, like in `sort-import`. Didn't have to implement the whole fix 🙈 .

And I'm wondering if it makes sense because node is moving to es6 `import` anyways and it will drop CommonJS eventually.
